### PR TITLE
updated to flutter 3.10.0

### PR DESCRIPTION
**Pull request by Risaroh**

### CODE REVIEW

**Comment by WiRight** [comment]
Wait for merge

**Comment by vanlooverenkoen** [comment]
`buildViewportChrome` does not exist anymore. We can remove the content of the ScrollBehaviour completely

**Comment by Risaroh** [comment]
@vanlooverenkoen updated

**Comment by vanlooverenkoen** [comment]
Perfect! That will result in a better pub.dev score

**Comment by vanlooverenkoen** [comment]
3.0.0 is released. let me know if you need anything else

**Pull request merged**
